language: ruby
rvm:
  - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
script: CODECLIMATE_REPO_TOKEN=fe4858d82c8e23e77edb9f4e1968daa8cba7a9638c29376e28f82a079bbee54e bundle exec rake test
